version: "3.8"

services:
  post-service:
    image: circuloapp/post-service:latest
    expose:
      - "3004"
    networks:
      - default
    ports:
      - "3004:3004"
    env_file:
      - ./env/post-service.env

  auth-service:
    image: circuloapp/auth-service:latest
    expose:
      - "3002"
    networks:
      - default
    ports:
      - "3002:3002"
    env_file:
      - ./env/auth-service.env

  chat-service:
    image: circuloapp/chat-service:latest
    expose:
      - "3008"
      - "3010"
    networks:
      - default
    ports:
      - "3008:3008"
      - "3010:3010"
    env_file:
      - ./env/chat-service.env

  friends-service:
    image: circuloapp/friends-service:latest
    expose:
      - "3006"
    networks:
      - default
    ports:
      - "3006:3006"
    env_file:
      - ./env/friends-service.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      # Uncomment and provide correct paths to SSL certificates
      # - /path/to/ssl/certs:/etc/ssl/certs
      # - /path/to/ssl/private:/etc/ssl/private
    depends_on:
      - post-service
      - auth-service
      - chat-service
      - friends-service
# version: '3.8'

# services:
#   post-service:
#     image: 025066285253.dkr.ecr.ap-south-1.amazonaws.com/post-service:latest
#     expose:
#       - "3004"  # Expose port internally for Nginx to access
#     environment:
#       - CORS_ORIGIN=https://circulo-omega.vercel.app
#     networks:
#       - default
#     ports:
#       - "3004:3004"

#   auth-service:
#     image: 025066285253.dkr.ecr.ap-south-1.amazonaws.com/auth-service:latest
#     expose:
#       - "3002"  # Expose port internally for Nginx to access
#     networks:
#       - default
#     ports:
#       - "3002:3002"
#     environment:
#       - PORT=3002
#       - MONGO_URI=mongodb+srv://appcirculo:OpGy26TWASNviAf0@circulo.jlzwn4y.mongodb.net/circulo?retryWrites=true&w=majority
#       - CORS_ORIGIN=https://circulo-omega.vercel.app
#       - MAIL_EMAIL=appcirculo@gmail.com
#       - MAIL_PASSWORD=gdka cfpb udcu jloy
#       - ACCESS_TOKEN_SECRET=e48323df1c357d910e5ab9bf4fcf4f51b1af6cc7d9ac2bdd1e8cbc04b1e55efa0099d5d46e37185a87af29e1e741d818fb52ad2ab7cb65c5a94639d4ec11c1f7182625bce486ee6b533dc0dd732b7a542530b6cbe954802e63514829a6ed70900f7b576722dd764d1ad46a8693549e2693a232a135a62d50af7d5b1cfb82bb97
#       - REFRESH_TOKEN_SECRET=0c9a486dc1bf6f420939fe1f8a7a3dd194bb9a5b1e68e8d47b3534f8b3b4cb4a20f4a9ac2d3e3c2e8bbfd9b870451d3b9eac7e84e0ef302c5a8eac8b1b3de2d8
#       - LOCATION_API=AIzaSyAYf4phtT1fjl1T0NG4WeIo7egq3U_Wbps
#       - CLOUD_NAME=dwlegfkli
#       - API_KEY=185915473463246
#       - API_SECRET=Y5pZ91lSnL3eMRK6MY4CEwPNWw0
#       - MESSAGE_BROKER_URL=amqps://rhxroozf:nihKej7GplM-WUOtkEYVcKYiECrwi--5@puffin.rmq2.cloudamqp.com/rhxroozf

#   chat-service:
#     image: 025066285253.dkr.ecr.ap-south-1.amazonaws.com/chat-service:latest
#     expose:
#       - "3008"
#       - "3010"  # Expose ports internally for Nginx to access
#     environment:
#       - CORS_ORIGIN=https://circulo-omega.vercel.app
#     networks:
#       - default
#     ports:
#       - "3008:3008"
#       - "3010:3010"

#   friends-service:
#     image: 025066285253.dkr.ecr.ap-south-1.amazonaws.com/friends-service:latest
#     expose:
#       - "3006"  # Expose port internally for Nginx to access
#     environment:
#       - CORS_ORIGIN=https://circulo-omega.vercel.app
#     networks:
#       - default
#     ports:
#       - "3006:3006"

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#       - "443:443"
#     restart: always
#     volumes:
#       - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#       - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
#       - ./ssl:/etc/nginx/ssl
#       # Uncomment and provide correct paths to SSL certificates
#       # - /path/to/ssl/certs:/etc/ssl/certs
#       # - /path/to/ssl/private:/etc/ssl/private
#     depends_on:
#       - post-service
#       - auth-service
#       - chat-service
#       - friends-service

# #  networks:
#  #   default:
#   #    driver: bridge

# so how to change this docercompose yml
