name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the React app (ensure it's in production mode)
      - name: Build React App
        run: |
          echo "Building frontend service..."
          cd frontend && npm ci && npm run build
          echo "React app build complete!"

      # Build the Docker image with the production build of React
      - name: Build Docker image for frontend service
        run: |
          echo "Building Docker image for frontend service..."
          docker build -t frontend-service:latest -f frontend/Dockerfile .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          echo "Pushing frontend Docker image to DockerHub..."
          docker tag frontend-service:latest ${{ secrets.DOCKER_USERNAME }}/frontend-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-65-0-173-200.ap-south-1.compute.amazonaws.com << EOF
            docker image prune -a -f
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-service:latest
            docker-compose -f /home/ec2-user/circulo/docker-compose.yml up -d 
          EOF
